apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "capsule-addon-fluxcd.fullname" . }}
  labels:
    {{- include "capsule-addon-fluxcd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "capsule-addon-fluxcd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "capsule-addon-fluxcd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "capsule-addon-fluxcd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          args:
          - manager
          - --proxy-ca-path=/tmp/proxy-tls/{{ .Values.proxy.tls.secretKey }}
          - --proxy-url={{ .Values.proxy.url }}
          - --zap-log-level={{ default 4 .Values.options.logLevel }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12}}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp/proxy-tls
              name: proxy-tls
              readOnly: true
      volumes:
        - name: proxy-tls
          secret:
            defaultMode: 420
            secretName: {{ .Values.proxy.tls.secretName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
