linters-settings:
  cyclop:
    max-complexity: 27
  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/projectcapsule/capsule-addon-fluxcd) # Groups all imports with the specified Prefix.
  goconst:
    min-len: 2
    min-occurrences: 3
  goheader:
    template: |-
      Copyright 2020-2023 Project Capsule Authors.
      SPDX-License-Identifier: Apache-2.0
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true

linters:
  enable-all: true
  disable:
    - interfacer
    - godox
    - golint
    - scopelint
    - maligned
    - gochecknoglobals
    - gochecknoinits
    - exhaustivestruct
    - exhaustruct
    - ireturn
    - lll
    - nonamedreturns
    - wrapcheck
    - varnamelen

issues:
  exclude-rules:
  - path: /
    linters:
    - typecheck
