version: "2"
linters:
  default: all
  disable:
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - godox
    - ireturn
    - lll
    - nonamedreturns
    - varnamelen
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 27
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - $gostd
            - k8s.io/api
            - k8s.io/apimachinery
            - k8s.io/client-go
            - github.com/projectcapsule
            - github.com/go-logr/logr
            - github.com/pkg/errors
            - github.com/spf13/cobra
            - sigs.k8s.io/controller-runtime
    funlen:
      lines: 110
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    goheader:
      template: |-
        Copyright 2020-2024 Project Capsule Authors.
        SPDX-License-Identifier: Apache-2.0
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/projectcapsule/capsule-addon-flux)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
